### PR TITLE
converted to Atom editor theme

### PR DESCRIPTION
**Pull request by bowerman**

### CODE REVIEW

**Comment by mkdynamic** [comment]
Awesome! Thanks so much. Will merge shorty.

**Comment by mkdynamic** [comment]
@bowerman Might make sense to add this as a separate repo. TextMate 2 points to this repo to automatically include the TM theme via Git, so don't want to break that. Thoughts if I make a new `made-of-code-atom-theme` and add you as collaborator?

**Comment by bowerman** [comment]
Definitely, I was thinking the same thing, not necessary to add me.

**Comment by mkdynamic** [comment]
@bowerman Done. I don't use Atom, so I added you as a maintainer to that repo :)

**Pull request closed without merging**
